name: Publish Release

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - uses: HappyOnigiri/ReleaseActions/actions/publish-release@main
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          pr-body: ${{ github.event.pull_request.body }}
          update-major-tag: 'true'
          github-token: ${{ secrets.GH_TOKEN }}
